//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.01 at 10:38:52 PM CEST 
//

package edu.agh.rea.descriptors;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Car complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Car">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plates" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Car", propOrder = { "color", "brand", "plates" })
public class Car {

	@XmlElement(required = true)
	protected String color;
	@XmlElement(required = true)
	protected String brand;
	@XmlElement(required = true)
	protected String plates;

	/**
	 * Gets the value of the color property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getColor() {
		return color;
	}

	/**
	 * Sets the value of the color property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setColor(String value) {
		this.color = value;
	}

	/**
	 * Gets the value of the brand property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBrand() {
		return brand;
	}

	/**
	 * Sets the value of the brand property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBrand(String value) {
		this.brand = value;
	}

	/**
	 * Gets the value of the plates property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPlates() {
		return plates;
	}

	/**
	 * Sets the value of the plates property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPlates(String value) {
		this.plates = value;
	}
	
	@Override
	public int hashCode() {
		return getColor().hashCode();
	}

	@Override
	public boolean equals(Object obj) {
		Car car = (Car) obj;
		if(car.getBrand() == null){
			return true;
		}if(car.getColor() == null){
			return true;
		}
		if(car.getPlates() == null){
			return true;
		}
		return getBrand().equals(car.getBrand()) && getColor().equals(car.getColor()) && getPlates().equals(car.getPlates());
	}

	@Override
	public String toString() {
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.append("Car");
		if (getColor() != null)
			stringBuilder.append(" color : ").append(getColor());
		if (getBrand() != null)
			stringBuilder.append(" brand : ").append(getBrand());
		if (getPlates() != null)
			stringBuilder.append(" plates : ").append(getPlates());
		return stringBuilder.toString();
	}

}
