//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.01 at 10:38:52 PM CEST 
//


package edu.agh.rea.descriptors;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Event complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Event">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="weather" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="participantsNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="place" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="perpetrator" type="{}Person"/>
 *         &lt;element name="victim" type="{}Person"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Event", propOrder = {
    "weather",
    "participantsNumber",
    "place",
    "dateTime",
    "perpetrator",
    "victim"
})
public class Event {

	@XmlElement(required = true)
    protected String weather;
    protected Integer participantsNumber;
    @XmlElement(required = true)
    protected String place;
    @XmlElement(required = true)
    protected String dateTime;
    @XmlElement(required = true)
    protected Person perpetrator;
    @XmlElement(required = true)
    protected Person victim;

    /**
     * Gets the value of the weather property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeather() {
        return weather;
    }

    /**
     * Sets the value of the weather property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeather(String value) {
        this.weather = value;
    }

    /**
     * Gets the value of the participantsNumber property.
     * 
     */
    public Integer getParticipantsNumber() {
        return participantsNumber;
    }

    /**
     * Sets the value of the participantsNumber property.
     * 
     */
    public void setParticipantsNumber(Integer value) {
        this.participantsNumber = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlace(String value) {
        this.place = value;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateTime(String value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the perpetrator property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPerpetrator() {
        return perpetrator;
    }

    /**
     * Sets the value of the perpetrator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPerpetrator(Person value) {
        this.perpetrator = value;
    }

    /**
     * Gets the value of the victim property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getVictim() {
        return victim;
    }

    /**
     * Sets the value of the victim property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setVictim(Person value) {
        this.victim = value;
    }

}
